---
- name: BIG-IP SETUP
  hosts: lb
  connection: local
  gather_facts: false

  tasks:

    - name: Setup provider
      ansible.builtin.set_fact:
        provider:
          server: "{{ ansible_host }}"
          # user: "{{ f5_admin_user }}"
          # password: "{{ f5_admin_password }}"
          server_port: "{{ f5_admin_port }}"
          validate_certs: false

    - name: Find Active Machine
      f5networks.f5_modules.bigip_command:
        provider: "{{ provider }}"
        match: "any"
        warn: no
        commands:
          - bash -c "cat /var/prompt/ps1"
      register: result
  
    - debug:
        var: result.stdout

  #SSL Upload and Modification of VIP to use New Certificate 
    - name: SSL cert upload
      f5networks.f5_modules.bigip_ssl_certificate:
        provider: "{{ provider }}"
        name: "{{ ssl_cert[-4] }}_cert"
        content: "{{ lookup('file', ssl_cert) }}"
      when: 
      - '"Active" in result.stdout'
      - ssl_file_location is not defined

    - name: SSL key upload
      f5networks.f5_modules.bigip_ssl_key:
        provider: "{{ provider }}"
        name: "{{ ssl_key[-4] }}_key"
        content: "{{ lookup('file', ssl_key) }}"
      when: 
      - '"Active" in result.stdout'
      - ssl_file_location is not defined

    - name: SSL cert upload
      f5networks.f5_modules.bigip_ssl_certificate:
        provider: "{{ provider }}"
        name: "{{ ssl_cert[-4] }}_cert"
        content: "{{ lookup('file', ssl_file_location + ssl_cert) }}"
      when: 
      - '"Active" in result.stdout'
      - ssl_file_location is defined

    - name: SSL key upload
      f5networks.f5_modules.bigip_ssl_key:
        provider: "{{ provider }}"
        name: "{{ ssl_key[-4] }}_key"
        content: "{{ lookup('file', ssl_file_location + ssl_key) }}"
      when: 
      - '"Active" in result.stdout'
      - ssl_file_location is defined

    - name: Create a client SSL profile with a cert/key/chain setting
      f5networks.f5_modules.bigip_profile_client_ssl:
        provider: "{{ provider }}"
        state: present
        name: "{{ vip_name }}_ClientSSL_profile"
        cert_key_chain:
        - cert: "{{ ssl_cert[-4] }}_cert"
          key: "{{ ssl_key[-4] }}_key"
      when: '"Active" in result.stdout'

    - name: UPDATE A VIRTUAL SERVER
      f5networks.f5_modules.bigip_virtual_server:
        provider: "{{provider}}"
        name: "{{ vip_name }}"
        port: "443"
        profiles:
        - name: "{{ vip_name }}_ClientSSL_profile"
          context: client-side
        - oneconnect
        - http
      when: '"Active" in result.stdout'

    - name: SAVE RUNNING CONFIG ON BIG-IP
      f5networks.f5_modules.bigip_config:
        provider: "{{ provider }}"
        save: true
      when: '"Active" in result.stdout'

# #    - name: Syncronize Hosts
